### ISSUE TITLE
Add XML file reader to CIM-Graph

### ISSUE THREAD

**Issue by AAndersn** [PNNL-CIM-Tools/CIM-Graph#32]
Create a ConnectionInterface object that can use xsdata or other library to read from an xml file and create python objects with all attributes in the file.

**Comment by craig8** [comment]
the or other library confuses me in this.  So we are given a hydrated xml file that has a model in it and we are creating a graph from that xml...NOT a schema because we have one  of those, but data that has been exported by either this tool or another.

Is that what we are doing in this issue?

**Comment by AAndersn** [comment]
Correct. We are currently doing that with curl command in shell for blazegraph. Doesn't work for any other databases. 

Idea is that instead of saying FeederModel(read_connection=blazegraph) we could do FeederModel(read_connection=XMLReader("feeder.xml"))

We can figure out exact syntax as we go

**Comment by AAndersn** [comment]
Support for direct reading of XML files with defense against XML vulnerabilities (https://docs.python.org/3/library/xml.html#xml-vulnerabilities) has been added as a new database connection in https://github.com/PNNL-CIM-Tools/CIM-Graph/blob/feature/68/cimgraph/databases/fileparsers/xml_parser.py

**Comment by AAndersn** [comment]
some additional work is needed to support both `rdf:ID="_UUID-STRING` and `rdf:about="urn:uuid:UUID-STRING`. Currently only the later is supported for use with feature/seto models

**Comment by AAndersn** [comment]
Fixed in #80
