### ISSUE TITLE
ACDCTerminal.sequenceNumber is not an int type

### ISSUE THREAD

**Issue by afisher1** [PNNL-CIM-Tools/CIM-Graph#4]
**Describe the bug**
Using CIM profile rc4_2021.
ACDCTerminal.sequenceNumber is documented as having a type None or int
checking and instance of this class attribute returned a type of str.

**Comment by AAndersn** [comment]
This will be fixed in https://github.com/PNNL-CIM-Tools/CIM-Graph/issues/5

**Comment by AAndersn** [comment]
This has been fixed in https://github.com/PNNL-CIM-Tools/CIM-Graph/blob/feature/68/cimgraph/databases/__init__.py#L97

**Comment by AAndersn** [comment]
Fixed in #80
