### ISSUE TITLE
Add attribute typing to query post-processing

### ISSUE THREAD

**Issue by AAndersn** [PNNL-CIM-Tools/CIM-Graph#5]
Need to enforce typing of attributes populated by query response. Currently all attribute values are strings (as returned from SPARQL).

CIM attributes contain typing in data_profile. This typing should be used to convert query response string to correct data type.

**Comment by craig8** [comment]
We can do this a variety of ways... perhaps https://docs.pydantic.dev/usage/dataclasses/

**Comment by AAndersn** [comment]
The new get_all_edges method in branch model_creator now has typing of enumerations in query response
