### ISSUE TITLE
Include the summary image in the package

### ISSUE THREAD

**Issue by craig8** [PNNL-CIM-Tools/CIM-Graph#56]
There is a reference in the README that is not available from the develop branch.  It will get taken care off when we go live, but if we want to make sure it is in the pypi readme we need to add it to the data or make it fully resolved.

**Comment by craig8** [comment]
@AAndersn thoughts?

**Comment by AAndersn** [comment]
@craig8  - it is at the same level as the readme -- does it need to be moved inside the package?

https://github.com/PNNL-CIM-Tools/CIM-Graph/blob/develop/cim_graph_structure.png

**Comment by craig8** [comment]
I am saying https://pypi.org/project/cim-graph/ doesn't have the image.  So we can put a full path link to https://github.com/PNNL-CIM-Tools/CIM-Graph/blob/develop/cim_graph_structure.png in the readme and fix the issue.

**Comment by AAndersn** [comment]
Fixed in #80
