### ISSUE TITLE
PowerTransformerEnd.connectionKind returns a List[str]

### ISSUE THREAD

**Issue by afisher1** [PNNL-CIM-Tools/CIM-Graph#6]
**Describe the bug**
Using CIM profile rc4_2021. 
PowerTransformerEnd.connectionKind is typed as an instance of the WindingConnection Enum but contains a List[str].

**Comment by craig8** [comment]
Will be fixed as part of #5

**Comment by afisher1** [comment]
talking with @AAndersn this is gonna need to be fixed for all Enum typed attributes.
