### ISSUE TITLE
When creating a connection with RDFlib allow no filename for new models

### ISSUE THREAD

**Issue by AAndersn** [PNNL-CIM-Tools/CIM-Graph#62]
Enable bypass of rdflib read of CIM XML model for creation of new models

**Comment by craig8** [comment]
@AAndersn there should be a PR with this in it rather than a push to develop

**Comment by AAndersn** [comment]
@craig8  - yeah just noticed that when I came back to make PR after lunch :)

**Comment by AAndersn** [comment]
Fixed in #80
